### ISSUE TITLE
How to use it with Visual Studio 2013?

### ISSUE THREAD

**Issue by ppaul** [matijagrcic/AngularJS-Intellisense-For-Visual-Studio#6]
I couldn't find the menus in options

**Comment by matijagrcic** [comment]
Angular is supported by Visual Studio 2013, take a look http://www.asp.net/visual-studio/overview/2013/visual-studio-2013-web-editor-features-html5 and http://webessentials.uservoice.com/forums/140520-general/suggestions/3487580-intellisense-for-angularjs. Also i would recommend that you install http://sidewaffle.com/ as it contains several great item templates and snippets for AngularJS. Find out more http://www.johnpapa.net/get-angular-durandal-and-javascript-templates-with-sidewaffle/
